sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

env:
  - PROJECT=directus VARIANT=apache

jobs:
  include:
    - stage: build
      script: ./tusk build $PROJECT $VARIANT
    - stage: publish
      script: ./tusk build --push $PROJECT $VARIANT

stages:
  - name: build
    if: branch != master
  - name: publish
    if: branch = master
