sudo: required
language: minimal

services:
  - docker

before_install:
  #- curl -sL https://git.io/tusk | bash -s -- -b . latest
  - echo "$DOCKER_TEST" | docker login -u "$DOCKER_TEST" --password-stdin

git:
  depth: 1
  quiet: true

script:
  - export TRAVIS_TAG=1.0.0
  - chmod +x ./bin/build && ./bin/build
  - docker images

branches:
  only:
    - refactor/full
    - /^\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+-pre$/
