sudo: required
language: minimal

services:
  - docker

#before_install:
#  - echo "$DOCKER_USERNAME" | docker login -u "$DOCKER_PASSWORD" --password-stdin

git:
  depth: 1
  quiet: true

script:
  - export TRAVIS_TAG=1.0.0
  - ./bin/build
  - docker images

branches:
  only:
    - refactor/full
    - /^\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+-pre$/
