sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

env:
  - PROJECT=directus VARIANT=apache

branches:
  only:
    - master

script:
  - ./tusk build --push $PROJECT $VARIANT
