sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

git:
  depth: 1
  quiet: true

env:
  - BASE=apache
  - BASE=nginx
  - BASE=caddy

script:
  - echo "tusk base --kind ${BASE} --version ${TRAVIS_TAG}"

branches:
  only:
    - refactor/full
    - /^v\d+\.\d+\.\d+$/
