sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

env:
  - PROJECT=directus VARIANT=apache

jobs:
  include:
    stages:
      - name: build
        if: branch != master
        script:
          - ./tusk build $PROJECT $VARIANT
      - name: build and push
        if: branch = master
        script:
          - ./tusk build --push $PROJECT $VARIANT
