sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

env:
  - PROJECT=directus VARIANT=apache

stages:
  - name: build
    script: ./tusk build $PROJECT $VARIANT
    if: branch != master
  - name: publish
    script: ./tusk build --push $PROJECT $VARIANT
    if: branch = master
