sudo: required
language: minimal

services:
  - docker

before_install:
  - curl -sL https://git.io/tusk | bash -s -- -b . latest

git:
  depth: 1
  quiet: true

script:
  - tusk --help

branches:
  only:
    - refactor/full
    - /^v\d+\.\d+\.\d+$/
