sudo: required
language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

git:
  depth: 1
  quiet: true

script:
  - ./bin/build

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+\.\d+$/
    - /^\d+\.\d+\.\d+-pre$/
