version: "3"
services:
  #
  # Database
  #
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "directus"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_ROOT_PASSWORD: "directus"
    ports:
      - 3306:3306

  #
  # API instance.
  # This should serve our api requests and won't work before database
  # is properly installed by running the installer.
  #
  api:
    image: directus/api:v2-apache
    ports:
      - "8080:80"
    environment:
      # App
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_APP_TIMEZONE: "America/Sao_Paulo"

      # These are now required, make sure to always set
      # to something unique while in production
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"

      # Database
      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"

      #
      # These are highly recommended for proper cloud native
      # installations, but not in this example
      #
      # Storage
      #DIRECTUS_STORAGE_ADAPTER: "s3"
      #DIRECTUS_STORAGE_ROOT: "/images/"
      #DIRECTUS_STORAGE_ROOTURL: "http://cdn.localtest.me/images"
      #DIRECTUS_STORAGE_THUMBROOT: "/images/thumbs/"
      #DIRECTUS_STORAGE_KEY: "storage_key"
      #DIRECTUS_STORAGE_SECRET: "storage_secret"
      #DIRECTUS_STORAGE_REGION: "us-east-1"
      #DIRECTUS_STORAGE_BUCKET: "cdn.localtest.me"

    # Uploads gets saved in uploads folder
    volumes:
      - ./uploads/:/var/www/public/uploads/

    links:
      - mysql:mysql

  #
  # APP instance.
  # This is our graphical management interface.
  #
  app:
    image: directus/app:v7-node
    ports:
      - "8090:80"
    environment:
      # Endpoints
      DIRECTUS_APP_TITLE: "Example"
      DIRECTUS_APP_URL: "http://localhost:8080/_/"
