apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus-app
  labels:
    app: directus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus-app
  template:
    metadata:
      labels:
        app: directus-app
    spec:
      containers:
        - name: directus-app
          image: directus/app:v7-node
          envFrom:
          - configMapRef:
              name: directus-app-configmap
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: directus-app
  name: directus-app-loadbalancer
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31017
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: directus-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
