
version: "3"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
   mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: "directus"
        MYSQL_USER: "directus"
        MYSQL_PASSWORD: "directus"
        MYSQL_ROOT_PASSWORD: "directus"
      ports:
        - 3306:3306
  api:
    image: directus/api:v2-apache
    ports:
      - "8080:80"
    links:
      - redis
    environment:
      DIRECTUS_APP_ENV: "production"
      DIRECTUS_APP_TIMEZONE: "Europe/Madrid"

      # These are now required, make sure to always set
      # to something unique while in production
      DIRECTUS_AUTH_PUBLICKEY: "some random secret"
      DIRECTUS_AUTH_SECRETKEY: "another random secret"

      DIRECTUS_DATABASE_HOST: "mysql"
      DIRECTUS_DATABASE_PORT: "3306"
      DIRECTUS_DATABASE_NAME: "directus"
      DIRECTUS_DATABASE_USERNAME: "directus"
      DIRECTUS_DATABASE_PASSWORD: "directus"

      DIRECTUS_CACHE_ENABLED: "true"
      DIRECTUS_CACHE_RESPONSETTL: "604800" # 1 week
      DIRECTUS_CACHE_POOL_ADAPTER: "redis"
      DIRECTUS_CACHE_POOL_HOST: "redis"
      DIRECTUS_CACHE_POOL_PORT: "6379"

      DIRECTUS_STORAGE_ADAPTER: "s3"
      DIRECTUS_STORAGE_ROOT: "/pub/directus/originals"
      DIRECTUS_STORAGE_ROOTURL: "http://minio.company.private/112233/pub/directus/originals"
      DIRECTUS_STORAGE_THUMB_ROOT: "/pub/directus/thumbnails"
      DIRECTUS_STORAGE_KEY: "user"
      DIRECTUS_STORAGE_SECRET: "secret"
      DIRECTUS_STORAGE_VERSION: "latest"
      DIRECTUS_STORAGE_BUCKET: "1122333"
      DIRECTUS_STORAGE_REGION: ""
      DIRECTUS_STORAGE_ENDPOINT: "http://minio.company.private"

  app:
    image: directus/app:v7-node
    ports:
      - "8090:80"
    environment:
      DIRECTUS_APP_TITLE: "Directus"
      DIRECTUS_APP_URL: "http://localhost:8080/_/"
